baseURL = 'https://AlpNuhoglu.github.io/personal-health-website/'
languageCode = 'en-us'
title = 'Personal Health Data Analysis'
theme = 'hugo-coder'
pagination.pagerSize = 10  # <- Updated this from 'paginate' for compatibility

[params]
    author = "Alp Nuhoglu"
    description = "A comprehensive analysis of personal health data, including step counts, calorie intake, and gym attendance."
    keywords = ["Health", "Fitness", "Data Analysis", "Visualization"]
    favicon = "favicon.ico"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNumbers = true
    style = "dracula"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "analyses"
    name = "Analyses"
    url = "/analyses/"
    weight = 2
